baseURL: "https://tiangonglab.github.io"
title: "å¤©å·¥å®éªŒå®¤"
copyright: "Â© [å¤©å·¥å®éªŒå®¤](https://poc.qianxin.com/home)"
languageCode: "zh"
defaultContentLanguage: "zh"
theme: "papermod"

menu:
  main:
    - name: å½’æ¡£
      url: archives
      weight: 5
    - name: æ ‡ç­¾
      url: tags/
      weight: 10
    - name: ç ´å£³å®˜ç½‘
      url: https://poc.qianxin.com/home
params:
  description: "å¥‡å®‰ä¿¡å¤©å·¥å®éªŒå®¤ï½œäº’è”ç½‘åŸºç¡€è®¾æ–½æ¼æ´æŒ–æ˜"
  author: å¥‡å®‰ä¿¡å¤©å·¥å®éªŒå®¤
  ShowShareButtons: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  disableThemeToggle: true
  defaultTheme: dark
  homeInfoParams:
      Title: "å¥‡å®‰ä¿¡å¤©å·¥å®éªŒå®¤æŠ€æœ¯åšå®¢"
      Content: >
        ğŸ‘‹ å¥‡å®‰ä¿¡å¤©å·¥å®éªŒå®¤ï¼Œèšç„¦çœŸå®ä¸–ç•Œæ¼æ´åˆ†æã€‚æ¼æ´ç ”ç©¶æˆæœæ›¾å‘è¡¨äºDEFCONã€BlackHatã€GeekConã€HITBã€ACM CCSã€Usenixã€EuroS&Pã€RAIDç­‰å›½é™…é‡é‡çº§ä¼šè®®ã€‚
        
        - å›¢é˜Ÿç ”å‘çš„ç ´å£³å¹³å°ï¼Œæä¾›åŸºäºæŸ¥è¯¢ã€é¢å‘å›¢é˜Ÿåä½œçš„æ¼æ´è¾…åŠ©åˆ†æèƒ½åŠ›ã€‚
        
  socialIcons:
    - name: github
      title: Follow on Github
      url: "https://github.com/tiangonglab"
    - name: X
      title: Follow on X/Twitter
      url: "https://x.com/TianGongLab"
    # - name: wechat
    #   title: Follow on WeChat
    #   url: "https://ko-fi.com/adityatelange"

  label:
    text: "å¤©å·¥å®éªŒå®¤"
    icon: /logo/logo3.png
    iconHeight: 100